'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _cfx = require('cfx.redux-types');

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

// Generated by CoffeeScript 2.0.0-beta2
var crudActionsTypes;

crudActionsTypes = function crudActionsTypes(routeName) {
  var i, kw, len, r, ref, ref1, ref2, ref3, ref4;
  routeName = routeName.toUpperCase();
  r = {};
  ref = ['FETCH', 'CREATE', 'UPDATE', 'DELETE'];
  for (i = 0, len = ref.length; i < len; i++) {
    var _Object$assign;

    kw = ref[i];
    Object.assign(r, (_Object$assign = {}, _defineProperty(_Object$assign, ref1 = routeName + '_' + kw, ref1), _defineProperty(_Object$assign, ref2 = routeName + '_' + kw + '_START', ref2), _defineProperty(_Object$assign, ref3 = routeName + '_' + kw + '_SUCCESS', ref3), _defineProperty(_Object$assign, ref4 = routeName + '_' + kw + '_ERROR', ref4), _Object$assign));
  }
  return (0, _cfx.toActionsTypes)(r);
};

exports.default = { crudActionsTypes: crudActionsTypes };

